### ISSUE TITLE
Missing CSS for sub-sub-optimum meter value

### ISSUE THREAD

**Issue by eclarke12** [death-save/combat-carousel#161]
Missing the following CSS:
```css
#combat-carousel meter::-webkit-meter-even-less-good-value {
    background: var(--sub-sub-optimum);
}
```
